name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get system dependencies
      run: sudo apt update && sudo apt install libvirt-dev

    - name: Install packer
      run: |
        wget -q https://releases.hashicorp.com/packer/1.5.6/packer_1.5.6_linux_amd64.zip
        unzip packer_1.5.6_linux_amd64.zip
        sudo mv packer /usr/local/bin/packer
        packer version

    - name: Get dependencies
      run: go mod download -x

    - name: Test
      run: make test

    - name: Validate
      run: |
        mkdir ${HOME}/.packer.d/plugins
        make validate
